---
  - name: APP | Clone project
    git:
      repo: https://git.dtplabs.in/humbertho.mattar/dev-batch-job.git
      dest: /home/vagrant/dev-batch-job/
      clone: yes
      update: yes
    become: yes
    become_user: vagrant
  
  - name: Install requirements
    pip: 
      requirements: /home/vagrant/dev-batch-job/requirements.txt
      virtualenv: /home/vagrant/dev-batch-job/.env
      virtualenv_python: python3
    become: yes
    become_user: vagrant