---
- name: Configure an python enviroment, for an generic-job
  hosts: all
  connection: local
  become: yes
  become_user: root
  become_method: sudo
  vars_files:
    - vars/main.yml

  roles:
  - default
  - application